# Generated by Django 6.0.6 on 2026-06-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicalhistory',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
