# Generated by Django 6.0.6 on 2026-06-29 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patientmedicalhistory_notes_patientvisit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_carrier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_policy',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='PatientBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(blank=True, default='', max_length=50)),
                ('receipt_id', models.CharField(blank=True, default='', max_length=50)),
                ('consultation_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('laboratory_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_status', models.CharField(default='none', max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-billing_id'],
            },
        ),
    ]
