# Generated by Django 6.0.6 on 2026-07-10 05:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_address_patientprofile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSmartWatchDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('is_connected', models.BooleanField(default=True)),
                ('battery_level', models.IntegerField(default=100)),
                ('last_sync', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='smartwatch_device', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientSmartWatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heart_rate', models.IntegerField(default=72)),
                ('bp_systolic', models.IntegerField(default=120)),
                ('bp_diastolic', models.IntegerField(default=80)),
                ('spo2', models.IntegerField(default=98)),
                ('steps', models.IntegerField(default=0)),
                ('calories', models.IntegerField(default=0)),
                ('sleep_duration', models.FloatField(default=0.0)),
                ('distance', models.FloatField(default=0.0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartwatch_data', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('patient', 'date')},
            },
        ),
    ]
