# Generated by Django 6.0.6 on 2026-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='frequency',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
