# Generated by Django 6.0.6 on 2026-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescriptionmedicine_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='route',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
