# Generated by Django 6.0.6 on 2026-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescriptionmedicine_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
