# Generated by Django 6.0.6 on 2026-06-22 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_id', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=255)),
                ('diagnosis', models.TextField()),
                ('consultation_date', models.DateField(default=django.utils.timezone.now)),
                ('symptoms', models.TextField()),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-consultation_date'],
            },
        ),
    ]
