# Generated by Django 6.0.6 on 2026-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultation_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient_id',
            field=models.CharField(max_length=50),
        ),
    ]
