# Generated by Django 6.0.6 on 2026-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_labrequest_appointment_id_labrequest_doctor_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='patient_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
