# Generated by Django 6.0.6 on 2026-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_alter_labrequest_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='labrequest',
            name='patient_id',
            field=models.CharField(max_length=50),
        ),
    ]
