# Generated by Django 6.0.6 on 2026-06-22 09:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appt_id', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=255)),
                ('dept_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_slot', models.CharField(max_length=50)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('type', models.CharField(choices=[('Doctor Checkup', 'Doctor Checkup'), ('Laboratory Test', 'Laboratory Test'), ('Emergency Patient', 'Emergency Patient')], default='Doctor Checkup', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
    ]
