# Generated by Django 6.0.6 on 2026-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorleaverequest_doctorreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleaverequest',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
