# Generated by Django 6.0.6 on 2026-07-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctorleaverequest_remarks'),
        ('laboratory', '0005_labrequest_appointment_id_labrequest_doctor_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorleaverequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='laboratory.labtechnicianprofile'),
        ),
        migrations.AlterField(
            model_name='doctorleaverequest',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='doctors.doctorprofile'),
        ),
    ]
