# Generated by Django 6.0.6 on 2026-07-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorleaverequest_technician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
