# Generated by Django 6.0.6 on 2026-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labtechnicianprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('results_ready', 'Results Ready'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
