# Generated by Django 6.0.6 on 2026-06-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_alter_labrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='consultation_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
