# Generated by Django 6.0.6 on 2026-06-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_labrequest_consultation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='appointment_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='doctor_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='tech_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
